language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - wget
      - zsh

script:
  - cargo build --verbose
  - cargo test --verbose
  - mkdir -p smoke
  - wget https://raw.githubusercontent.com/grml/grml-etc-core/master/etc/zsh/zshrc -O smoke/vanilla-grml-zshrc
  - zsh -c "source smoke/vanilla-grml-zshrc && eval $(cargo run -- print-zsh-setup 2>/dev/null)"

notifications:
  email:
    on_success: never
    on_failure: always
